# Generated by Django 3.2.3 on 2021-05-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usdrate',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
