# Generated by Django 3.2.3 on 2021-05-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id_stuff',
            new_name='is_stuff',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id_verified',
            new_name='is_verified',
        ),
    ]
